% DesignANN
%
% C. T. Clarke based on work by Assad al Shueli
% Edited by L F Tiong 06/05/2016
%
% This code configures Matlab and trains a set of ANNs to detect APs at
% particular velocities.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Parameter setup
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Basic System parameters
Parameters = struct (                 ...
   'Electrodes',              11    , ...
   'ElectrodeSpacing',      3e-3    , ...
   'SamplingFrequency',      1e5    , ...
   'ActionPotentialType',    'tmap2', ...
   'StartTestVelocity',       10    , ...
   'StepTestVelocity',         1    , ...
   'EndTestVelocity',        120    , ...
   'MatchRepeats',            20    , ...
   'NoiseLevel',               0    , ...
   'AnnLength',          [120, 1]   , ...
   'HiddenLayerSize',         [1]   , ...
   'ActivationFcn1',       'tansig' , ...
   'ActivationFcn2',       'purelin', ...
   'TrainingMethod',       'trainlm', ...
   'TargetOutput',           'pulse', ...
   'MaxIterations',          100    , ...
   'MinError',                 0    );

% ANN velocities to train for
AnnVelocities = [20, 50, 90];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Design each ANN
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ANN = DesignAnn (AnnVelocities, Parameters);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Analyse the resultant ANNs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
AnalyseAnn(ANN, AnnVelocities, Parameters);
